console.log("Meu primeiro projeto no console");

            var firstName = "Luiz" ;
            console.log(firstName);

            var lastName = "Felipe" ;
            console.log(lastName)
            
            var fullName = firstName.concat(lastName);
            console.log(fullName);

            var a = 10;
            var b = 5;

            var add = a + b;
            console.log(add);

            var sub =  a - b;
            console.log(sub);

            var multiple = a * b;
            console.log();

            var divide = a / b ;
            console.log(divide);